import { NextRequest, NextResponse } from 'next/server'

export async function GET(request: NextRequest) {
    try {
        // Query the database using the query helper
        const result = {
            rows: [
                {
                    metadata: {
                        url: 'https://codybontecou.com/',
                        timestamp: '2025-02-16T21:12:23.382Z',
                    },
                    rawData: {
                        url: 'https://codybontecou.com/',
                        mobileLighthouseSummary: {
                            performance: 100,
                            accessibility: 96,
                            seo: 100,
                            bestPractices: 100,
                            issues: [
                                'Redirects HTTP traffic to HTTPS',
                                'First Contentful Paint',
                                'First Meaningful Paint',
                                'Total Blocking Time',
                                'Max Potential First Input Delay',
                                'Time to Interactive',
                                'User Timing marks and measures',
                                'Avoid multiple page redirects',
                                'Lazy load third-party resources with facades',
                                'Largest Contentful Paint image was not lazily loaded',
                                'Avoid large layout shifts',
                                'Avoid non-composited animations',
                                'Preload Largest Contentful Paint image',
                                '`[accesskey]` values are unique',
                                '`button`, `link`, and `menuitem` elements have accessible names',
                                'Elements with `role="dialog"` or `role="alertdialog"` have accessible names.',
                                '`[aria-hidden="true"]` elements do not contain focusable descendents',
                                'ARIA input fields have accessible names',
                                'ARIA `meter` elements have accessible names',
                                'ARIA `progressbar` elements have accessible names',
                                'Elements with an ARIA `[role]` that require children to contain a specific `[role]` have all required children.',
                                '`[role]`s are contained by their required parent element',
                                'Elements with the `role=text` attribute do not have focusable descendents.',
                                'ARIA toggle fields have accessible names',
                                'ARIA `tooltip` elements have accessible names',
                                'ARIA `treeitem` elements have accessible names',
                                'The page contains a heading, skip link, or landmark region',
                                "`<dl>`'s contain only properly-ordered `<dt>` and `<dd>` groups, `<script>`, `<template>` or `<div>` elements.",
                                'Definition list items are wrapped in `<dl>` elements',
                                'ARIA IDs are unique',
                                'All heading elements contain content.',
                                'No form fields have multiple labels',
                                '`<frame>` or `<iframe>` elements have a title',
                                '`<html>` element has an `[xml:lang]` attribute with the same base language as the `[lang]` attribute.',
                                'Image elements have `[alt]` attributes',
                                'Image elements do not have `[alt]` attributes that are redundant text.',
                                'Input buttons have discernible text.',
                                '`<input type="image">` elements have `[alt]` text',
                                'Elements with visible text labels have matching accessible names.',
                                'Form elements have associated labels',
                                'Links rely on color to be distinguishable.',
                                'The document does not use `<meta http-equiv="refresh">`',
                                '`<object>` elements have alternate text',
                                'Select elements have associated label elements.',
                                'Skip links are focusable.',
                                'Tables have different content in the summary attribute and `<caption>`.',
                                'Tables use `<caption>` instead of cells with the `[colspan]` attribute to indicate a caption.',
                                '`<td>` elements in a large `<table>` have one or more table headers.',
                                'Cells in a `<table>` element that use the `[headers]` attribute refer to table cells within the same table.',
                                '`<th>` elements and elements with `[role="columnheader"/"rowheader"]` have data cells they describe.',
                                '`[lang]` attributes have a valid value',
                                '`<video>` elements contain a `<track>` element with `[kind="captions"]`',
                                'Custom controls have associated labels',
                                'Custom controls have ARIA roles',
                                'User focus is not accidentally trapped in a region',
                                'Interactive controls are keyboard focusable',
                                'Interactive elements indicate their purpose and state',
                                'The page has a logical tab order',
                                "The user's focus is directed to new content added to the page",
                                'Offscreen content is hidden from assistive technology',
                                'HTML5 landmark elements are used to improve navigation',
                                'Visual order on the page follows DOM order',
                                'robots.txt is valid',
                                'Document has a valid `rel=canonical`',
                                'Structured data is valid',
                            ],
                        },
                        desktopLighthouseSummary: {
                            performance: 100,
                            accessibility: 96,
                            seo: 100,
                            bestPractices: 100,
                            issues: [
                                'Redirects HTTP traffic to HTTPS',
                                'First Meaningful Paint',
                                'User Timing marks and measures',
                                'Avoid multiple page redirects',
                                'Lazy load third-party resources with facades',
                                'Largest Contentful Paint image was not lazily loaded',
                                'Avoid large layout shifts',
                                'Avoid non-composited animations',
                                'Preload Largest Contentful Paint image',
                                '`[accesskey]` values are unique',
                                '`button`, `link`, and `menuitem` elements have accessible names',
                                'Elements with `role="dialog"` or `role="alertdialog"` have accessible names.',
                                '`[aria-hidden="true"]` elements do not contain focusable descendents',
                                'ARIA input fields have accessible names',
                                'ARIA `meter` elements have accessible names',
                                'ARIA `progressbar` elements have accessible names',
                                'Elements with an ARIA `[role]` that require children to contain a specific `[role]` have all required children.',
                                '`[role]`s are contained by their required parent element',
                                'Elements with the `role=text` attribute do not have focusable descendents.',
                                'ARIA toggle fields have accessible names',
                                'ARIA `tooltip` elements have accessible names',
                                'ARIA `treeitem` elements have accessible names',
                                'The page contains a heading, skip link, or landmark region',
                                "`<dl>`'s contain only properly-ordered `<dt>` and `<dd>` groups, `<script>`, `<template>` or `<div>` elements.",
                                'Definition list items are wrapped in `<dl>` elements',
                                'ARIA IDs are unique',
                                'All heading elements contain content.',
                                'No form fields have multiple labels',
                                '`<frame>` or `<iframe>` elements have a title',
                                '`<html>` element has an `[xml:lang]` attribute with the same base language as the `[lang]` attribute.',
                                'Image elements have `[alt]` attributes',
                                'Image elements do not have `[alt]` attributes that are redundant text.',
                                'Input buttons have discernible text.',
                                '`<input type="image">` elements have `[alt]` text',
                                'Elements with visible text labels have matching accessible names.',
                                'Form elements have associated labels',
                                'Links rely on color to be distinguishable.',
                                'The document does not use `<meta http-equiv="refresh">`',
                                '`<object>` elements have alternate text',
                                'Select elements have associated label elements.',
                                'Skip links are focusable.',
                                'Tables have different content in the summary attribute and `<caption>`.',
                                'Tables use `<caption>` instead of cells with the `[colspan]` attribute to indicate a caption.',
                                '`<td>` elements in a large `<table>` have one or more table headers.',
                                'Cells in a `<table>` element that use the `[headers]` attribute refer to table cells within the same table.',
                                '`<th>` elements and elements with `[role="columnheader"/"rowheader"]` have data cells they describe.',
                                '`[lang]` attributes have a valid value',
                                '`<video>` elements contain a `<track>` element with `[kind="captions"]`',
                                'Custom controls have associated labels',
                                'Custom controls have ARIA roles',
                                'User focus is not accidentally trapped in a region',
                                'Interactive controls are keyboard focusable',
                                'Interactive elements indicate their purpose and state',
                                'The page has a logical tab order',
                                "The user's focus is directed to new content added to the page",
                                'Offscreen content is hidden from assistive technology',
                                'HTML5 landmark elements are used to improve navigation',
                                'Visual order on the page follows DOM order',
                                'Reduce unused JavaScript',
                                'Document uses legible font sizes',
                                'robots.txt is valid',
                                'Document has a valid `rel=canonical`',
                                'Structured data is valid',
                            ],
                        },
                    },
                    analysis: {
                        business_type: 'Personal Blog',
                        layout_score: 7,
                        color_score: 8,
                        typography_score: 8,
                        clarity_score: 9,
                        layout_feedback:
                            'The layout is clean and straightforward, focusing on readability and simplicity. However, the margin between sections could be slightly increased to enhance separation and visual comfort.',
                        color_feedback:
                            'The color scheme is minimalistic, using mainly black and white, which promotes readability. Consider using a complementary color for links to make them stand out more distinctively.',
                        typography_feedback:
                            'Typography is clean and legible with a good hierarchy. Heading fonts are bold and distinct, but body text size could be slightly increased for better readability on different devices.',
                        clarity_feedback:
                            "The content is clearly presented with a good use of whitespace. Sections like 'Topics' and 'Writing' are well-organized and easy to navigate.",
                        top_5_suggestions: [
                            'Increase spacing between sections to improve visual hierarchy.',
                            'Use a distinct color for hyperlinks to enhance visibility.',
                            'Increase the body text size slightly for better readability.',
                            'Consider adding icons or visual elements to enrich visual interest.',
                            'Ensure responsive design for optimal viewing on all devices.',
                        ],
                        overall_score: 8,
                    },
                },
            ],
        }

        if (result.rows.length === 0) {
            return NextResponse.json(
                { error: 'URL not found' },
                { status: 404 }
            )
        }

        return NextResponse.json({
            success: true,
            data: result.rows[0],
        })
    } catch (error) {
        console.error('Error retrieving URL:', error)

        return NextResponse.json(
            { error: 'Internal server error' },
            { status: 500 }
        )
    }
}
