import { WebsiteAnalysis } from '@/types/WebsiteAnalysis'

export function getData(): WebsiteAnalysis {
    return {
        metadata: {
            url: 'https://www.roofbritehawaii.com/',
            timestamp: '2025-02-17T17:10:03.978Z',
        },
        rawData: {
            url: 'https://www.roofbritehawaii.com/',
            mobileLighthouseSummary: {
                performance: 69,
                accessibility: 98,
                seo: 92,
                bestPractices: 79,
                issues: [
                    'Redirects HTTP traffic to HTTPS',
                    'Largest Contentful Paint',
                    'First Meaningful Paint',
                    'Speed Index',
                    'Total Blocking Time',
                    'Max Potential First Input Delay',
                    'Cumulative Layout Shift',
                    'Time to Interactive',
                    'Uses third-party cookies',
                    'Minimize main-thread work',
                    'Lazy load third-party resources with facades',
                    'Largest Contentful Paint element',
                    'Largest Contentful Paint image was not lazily loaded',
                    'Avoid non-composited animations',
                    'Image elements do not have explicit `width` and `height`',
                    'Preload Largest Contentful Paint image',
                    '`[accesskey]` values are unique',
                    'Elements with `role="dialog"` or `role="alertdialog"` have accessible names.',
                    'ARIA input fields have accessible names',
                    'ARIA `meter` elements have accessible names',
                    'ARIA `progressbar` elements have accessible names',
                    'Elements with an ARIA `[role]` that require children to contain a specific `[role]` have all required children.',
                    '`[role]`s are contained by their required parent element',
                    'Elements with the `role=text` attribute do not have focusable descendents.',
                    'ARIA toggle fields have accessible names',
                    'ARIA `tooltip` elements have accessible names',
                    'ARIA `treeitem` elements have accessible names',
                    'The page contains a heading, skip link, or landmark region',
                    "`<dl>`'s contain only properly-ordered `<dt>` and `<dd>` groups, `<script>`, `<template>` or `<div>` elements.",
                    'Definition list items are wrapped in `<dl>` elements',
                    'ARIA IDs are unique',
                    'All heading elements contain content.',
                    'No form fields have multiple labels',
                    '`<frame>` or `<iframe>` elements have a title',
                    'Heading elements are not in a sequentially-descending order',
                    '`<html>` element has an `[xml:lang]` attribute with the same base language as the `[lang]` attribute.',
                    'Identical links have the same purpose.',
                    'Input buttons have discernible text.',
                    '`<input type="image">` elements have `[alt]` text',
                    'Document has a main landmark.',
                    'Links are distinguishable without relying on color.',
                    'The document does not use `<meta http-equiv="refresh">`',
                    '`<object>` elements have alternate text',
                    'Select elements have associated label elements.',
                    'Skip links are focusable.',
                    'Tables have different content in the summary attribute and `<caption>`.',
                    'Tables use `<caption>` instead of cells with the `[colspan]` attribute to indicate a caption.',
                    '`<td>` elements in a large `<table>` have one or more table headers.',
                    'Cells in a `<table>` element that use the `[headers]` attribute refer to table cells within the same table.',
                    '`<th>` elements and elements with `[role="columnheader"/"rowheader"]` have data cells they describe.',
                    '`[lang]` attributes have a valid value',
                    'Custom controls have associated labels',
                    'Custom controls have ARIA roles',
                    'User focus is not accidentally trapped in a region',
                    'Interactive controls are keyboard focusable',
                    'Interactive elements indicate their purpose and state',
                    'The page has a logical tab order',
                    "The user's focus is directed to new content added to the page",
                    'Offscreen content is hidden from assistive technology',
                    'HTML5 landmark elements are used to improve navigation',
                    'Visual order on the page follows DOM order',
                    'Serve static assets with an efficient cache policy',
                    'Avoid enormous network payloads',
                    'Reduce unused JavaScript',
                    'Remove duplicate modules in JavaScript bundles',
                    'Avoid serving legacy JavaScript to modern browsers',
                    'Issues were logged in the `Issues` panel in Chrome Devtools',
                    'Links do not have descriptive text',
                    'Structured data is valid',
                    'Page prevented back/forward cache restoration',
                ],
            },
            desktopLighthouseSummary: {
                performance: 93,
                accessibility: 98,
                seo: 92,
                bestPractices: 78,
                issues: [
                    'Redirects HTTP traffic to HTTPS',
                    'Largest Contentful Paint',
                    'First Meaningful Paint',
                    'Speed Index',
                    'Uses third-party cookies',
                    'Lazy load third-party resources with facades',
                    'Largest Contentful Paint element',
                    'Largest Contentful Paint image was not lazily loaded',
                    'Avoid long main-thread tasks',
                    'Avoid non-composited animations',
                    'Image elements do not have explicit `width` and `height`',
                    'Preload Largest Contentful Paint image',
                    '`[accesskey]` values are unique',
                    'Elements with `role="dialog"` or `role="alertdialog"` have accessible names.',
                    'ARIA input fields have accessible names',
                    'ARIA `meter` elements have accessible names',
                    'ARIA `progressbar` elements have accessible names',
                    'Elements with an ARIA `[role]` that require children to contain a specific `[role]` have all required children.',
                    '`[role]`s are contained by their required parent element',
                    'Elements with the `role=text` attribute do not have focusable descendents.',
                    'ARIA toggle fields have accessible names',
                    'ARIA `tooltip` elements have accessible names',
                    'ARIA `treeitem` elements have accessible names',
                    'The page contains a heading, skip link, or landmark region',
                    "`<dl>`'s contain only properly-ordered `<dt>` and `<dd>` groups, `<script>`, `<template>` or `<div>` elements.",
                    'Definition list items are wrapped in `<dl>` elements',
                    'ARIA IDs are unique',
                    'All heading elements contain content.',
                    'No form fields have multiple labels',
                    '`<frame>` or `<iframe>` elements have a title',
                    'Heading elements are not in a sequentially-descending order',
                    '`<html>` element has an `[xml:lang]` attribute with the same base language as the `[lang]` attribute.',
                    'Identical links have the same purpose.',
                    'Input buttons have discernible text.',
                    '`<input type="image">` elements have `[alt]` text',
                    'Document has a main landmark.',
                    'Links are distinguishable without relying on color.',
                    'The document does not use `<meta http-equiv="refresh">`',
                    '`<object>` elements have alternate text',
                    'Select elements have associated label elements.',
                    'Skip links are focusable.',
                    'Tables have different content in the summary attribute and `<caption>`.',
                    'Tables use `<caption>` instead of cells with the `[colspan]` attribute to indicate a caption.',
                    '`<td>` elements in a large `<table>` have one or more table headers.',
                    'Cells in a `<table>` element that use the `[headers]` attribute refer to table cells within the same table.',
                    '`<th>` elements and elements with `[role="columnheader"/"rowheader"]` have data cells they describe.',
                    '`[lang]` attributes have a valid value',
                    'Custom controls have associated labels',
                    'Custom controls have ARIA roles',
                    'User focus is not accidentally trapped in a region',
                    'Interactive controls are keyboard focusable',
                    'Interactive elements indicate their purpose and state',
                    'The page has a logical tab order',
                    "The user's focus is directed to new content added to the page",
                    'Offscreen content is hidden from assistive technology',
                    'HTML5 landmark elements are used to improve navigation',
                    'Visual order on the page follows DOM order',
                    'Serve static assets with an efficient cache policy',
                    'Avoid enormous network payloads',
                    'Reduce unused JavaScript',
                    'Remove duplicate modules in JavaScript bundles',
                    'Avoid serving legacy JavaScript to modern browsers',
                    'Issues were logged in the `Issues` panel in Chrome Devtools',
                    'Document uses legible font sizes',
                    'Links do not have descriptive text',
                    'Structured data is valid',
                    'Page prevented back/forward cache restoration',
                ],
            },
        },
        analysis: {
            business_type: 'Residential and Commercial Cleaning Service',
            layout_score: 5,
            color_score: 6,
            typography_score: 4,
            clarity_score: 5,
            layout_feedback:
                'The layout is slightly cluttered, with multiple sections competing for attention. Visual hierarchy is lacking, making it hard for users to know where to look first.',
            color_feedback:
                'Colors are somewhat effective but lack consistency. High contrast is present in some areas, but there are sections where text blends into the background, making it difficult to read.',
            typography_feedback:
                'The typography is inconsistent with varying font sizes and styles. The headline fonts are bold but not visually appealing or cohesive with other text elements.',
            clarity_feedback:
                'Content clarity suffers due to clutter and misalignment. The text is not always easy to read because of poor contrast and font selection.',
            top_5_suggestions: [
                'Improve the visual hierarchy by organizing sections more clearly and using larger, bold fonts for headings.',
                'Enhance color consistency and ensure text contrasts enough against backgrounds for readability.',
                'Choose a more unified typography style to give a professional and clean appearance.',
                'Increase whitespace to reduce clutter and make the page easier to navigate.',
                'Ensure images are in high resolution and clearly relevant to their respective text sections.',
            ],
            overall_score: 5,
        },
    }
}
