import { WebsiteAnalysis } from '@/types/WebsiteAnalysis'

export function getData(): WebsiteAnalysis {
    return {
        metadata: {
            url: 'https://catalinapoolsaz.com/',
            timestamp: '2025-02-17T17:28:48.035Z',
        },
        rawData: {
            url: 'https://catalinapoolsaz.com/',
            mobileLighthouseSummary: {
                performance: 47,
                accessibility: 92,
                seo: 77,
                bestPractices: 61,
                issues: [
                    'Redirects HTTP traffic to HTTPS',
                    'First Contentful Paint',
                    'Largest Contentful Paint',
                    'First Meaningful Paint',
                    'Speed Index',
                    'Total Blocking Time',
                    'Max Potential First Input Delay',
                    'Cumulative Layout Shift',
                    'Time to Interactive',
                    'Uses deprecated APIs',
                    'Uses third-party cookies',
                    'Minimize main-thread work',
                    'Reduce JavaScript execution time',
                    'Ensure text remains visible during webfont load',
                    'Lazy load third-party resources with facades',
                    'Largest Contentful Paint element',
                    'Avoid large layout shifts',
                    'Avoid non-composited animations',
                    'Image elements do not have explicit `width` and `height`',
                    'Preload Largest Contentful Paint image',
                    '`[accesskey]` values are unique',
                    '`button`, `link`, and `menuitem` elements have accessible names',
                    'Elements with `role="dialog"` or `role="alertdialog"` have accessible names.',
                    'ARIA input fields have accessible names',
                    'ARIA `meter` elements have accessible names',
                    'ARIA `progressbar` elements have accessible names',
                    'Elements with an ARIA `[role]` that require children to contain a specific `[role]` have all required children.',
                    '`[role]`s are contained by their required parent element',
                    'Elements with the `role=text` attribute do not have focusable descendents.',
                    'ARIA toggle fields have accessible names',
                    'ARIA `tooltip` elements have accessible names',
                    'ARIA `treeitem` elements have accessible names',
                    'Buttons have an accessible name',
                    'The page contains a heading, skip link, or landmark region',
                    "`<dl>`'s contain only properly-ordered `<dt>` and `<dd>` groups, `<script>`, `<template>` or `<div>` elements.",
                    'Definition list items are wrapped in `<dl>` elements',
                    'ARIA IDs are unique',
                    'No form fields have multiple labels',
                    '`<frame>` or `<iframe>` elements have a title',
                    'Heading elements are not in a sequentially-descending order',
                    '`<html>` element has an `[xml:lang]` attribute with the same base language as the `[lang]` attribute.',
                    'Identical links have the same purpose.',
                    'Image elements do not have `[alt]` attributes',
                    'Input buttons have discernible text.',
                    '`<input type="image">` elements have `[alt]` text',
                    'Form elements have associated labels',
                    'Document has a main landmark.',
                    'Links are distinguishable without relying on color.',
                    'The document does not use `<meta http-equiv="refresh">`',
                    '`<object>` elements have alternate text',
                    'Select elements have associated label elements.',
                    'Tables have different content in the summary attribute and `<caption>`.',
                    'Tables use `<caption>` instead of cells with the `[colspan]` attribute to indicate a caption.',
                    '`<td>` elements in a large `<table>` have one or more table headers.',
                    'Cells in a `<table>` element that use the `[headers]` attribute refer to table cells within the same table.',
                    '`<th>` elements and elements with `[role="columnheader"/"rowheader"]` have data cells they describe.',
                    '`[lang]` attributes have a valid value',
                    'Custom controls have associated labels',
                    'Custom controls have ARIA roles',
                    'User focus is not accidentally trapped in a region',
                    'Interactive controls are keyboard focusable',
                    'Interactive elements indicate their purpose and state',
                    'The page has a logical tab order',
                    "The user's focus is directed to new content added to the page",
                    'Offscreen content is hidden from assistive technology',
                    'HTML5 landmark elements are used to improve navigation',
                    'Visual order on the page follows DOM order',
                    'Serve static assets with an efficient cache policy',
                    'Avoid enormous network payloads',
                    'Defer offscreen images',
                    'Eliminate render-blocking resources',
                    'Reduce unused CSS',
                    'Reduce unused JavaScript',
                    'Serve images in next-gen formats',
                    'Enable text compression',
                    'Properly size images',
                    'Avoid serving legacy JavaScript to modern browsers',
                    'Avoid an excessive DOM size',
                    'Issues were logged in the `Issues` panel in Chrome Devtools',
                    'Does not use passive listeners to improve scrolling performance',
                    'Links do not have descriptive text',
                    'Links are not crawlable',
                    'Structured data is valid',
                    'Page prevented back/forward cache restoration',
                ],
            },
            desktopLighthouseSummary: {
                performance: 83,
                accessibility: 92,
                seo: 77,
                bestPractices: 59,
                issues: [
                    'Redirects HTTP traffic to HTTPS',
                    'First Contentful Paint',
                    'Largest Contentful Paint',
                    'First Meaningful Paint',
                    'Speed Index',
                    'Cumulative Layout Shift',
                    'Uses deprecated APIs',
                    'Uses third-party cookies',
                    'Preconnect to required origins',
                    'Ensure text remains visible during webfont load',
                    'Lazy load third-party resources with facades',
                    'Largest Contentful Paint element',
                    'Largest Contentful Paint image was not lazily loaded',
                    'Avoid long main-thread tasks',
                    'Avoid non-composited animations',
                    'Image elements do not have explicit `width` and `height`',
                    'Preload Largest Contentful Paint image',
                    '`[accesskey]` values are unique',
                    '`button`, `link`, and `menuitem` elements have accessible names',
                    'Elements with `role="dialog"` or `role="alertdialog"` have accessible names.',
                    'ARIA input fields have accessible names',
                    'ARIA `meter` elements have accessible names',
                    'ARIA `progressbar` elements have accessible names',
                    'Elements with an ARIA `[role]` that require children to contain a specific `[role]` have all required children.',
                    '`[role]`s are contained by their required parent element',
                    'Elements with the `role=text` attribute do not have focusable descendents.',
                    'ARIA toggle fields have accessible names',
                    'ARIA `tooltip` elements have accessible names',
                    'ARIA `treeitem` elements have accessible names',
                    'Buttons have an accessible name',
                    'The page contains a heading, skip link, or landmark region',
                    "`<dl>`'s contain only properly-ordered `<dt>` and `<dd>` groups, `<script>`, `<template>` or `<div>` elements.",
                    'Definition list items are wrapped in `<dl>` elements',
                    'ARIA IDs are unique',
                    'No form fields have multiple labels',
                    '`<frame>` or `<iframe>` elements have a title',
                    'Heading elements are not in a sequentially-descending order',
                    '`<html>` element has an `[xml:lang]` attribute with the same base language as the `[lang]` attribute.',
                    'Identical links have the same purpose.',
                    'Image elements do not have `[alt]` attributes',
                    'Input buttons have discernible text.',
                    '`<input type="image">` elements have `[alt]` text',
                    'Form elements have associated labels',
                    'Document has a main landmark.',
                    'Links are distinguishable without relying on color.',
                    'The document does not use `<meta http-equiv="refresh">`',
                    '`<object>` elements have alternate text',
                    'Select elements have associated label elements.',
                    'No element has a `[tabindex]` value greater than 0',
                    'Tables have different content in the summary attribute and `<caption>`.',
                    'Tables use `<caption>` instead of cells with the `[colspan]` attribute to indicate a caption.',
                    '`<td>` elements in a large `<table>` have one or more table headers.',
                    'Cells in a `<table>` element that use the `[headers]` attribute refer to table cells within the same table.',
                    '`<th>` elements and elements with `[role="columnheader"/"rowheader"]` have data cells they describe.',
                    '`[lang]` attributes have a valid value',
                    'Custom controls have associated labels',
                    'Custom controls have ARIA roles',
                    'User focus is not accidentally trapped in a region',
                    'Interactive controls are keyboard focusable',
                    'Interactive elements indicate their purpose and state',
                    'The page has a logical tab order',
                    "The user's focus is directed to new content added to the page",
                    'Offscreen content is hidden from assistive technology',
                    'HTML5 landmark elements are used to improve navigation',
                    'Visual order on the page follows DOM order',
                    'Serve static assets with an efficient cache policy',
                    'Avoid enormous network payloads',
                    'Defer offscreen images',
                    'Eliminate render-blocking resources',
                    'Reduce unused CSS',
                    'Reduce unused JavaScript',
                    'Serve images in next-gen formats',
                    'Enable text compression',
                    'Properly size images',
                    'Avoid serving legacy JavaScript to modern browsers',
                    'Avoid an excessive DOM size',
                    'Issues were logged in the `Issues` panel in Chrome Devtools',
                    'Document uses legible font sizes',
                    'Links do not have descriptive text',
                    'Links are not crawlable',
                    'Structured data is valid',
                    'Page prevented back/forward cache restoration',
                ],
            },
        },
        analysis: {
            business_type: 'Pool Maintenance Services',
            layout_score: 6,
            color_score: 7,
            typography_score: 5,
            clarity_score: 5,
            layout_feedback:
                'The layout uses a typical long-scroll design which is good for storytelling but lacks clear section demarcations. It creates a somewhat cluttered appearance. Better structuring could improve the flow and help users navigate more intuitively.',
            color_feedback:
                'The color scheme uses a combination of blue and yellow. While visually appealing, the contrast between text and background in some sections makes reading challenging, especially with text overlaid on images.',
            typography_feedback:
                'There is inconsistent use of fonts and sizes that disrupts readability. Some text is densely packed, making it hard to read, especially in areas with overlaid images.',
            clarity_feedback:
                'The page lacks clarity due to overlapping elements and excessive text in certain areas. Key messages and calls to action are not immediately obvious, detracting from user engagement.',
            top_5_suggestions: [
                'Improve text readability by increasing contrast and using larger fonts.',
                'Segment content into clearly defined sections with distinct headers.',
                'Provide more whitespace to reduce clutter and improve focus on key elements.',
                'Enhance navigation with a sticky menu or section links.',
                'Streamline content to focus on essential information, improving message clarity.',
            ],
            overall_score: 5.75,
        },
    }
}
